[project]
name = "eddy-cov"
version = "0.1.0"
description = "Testing eddy covariance data"
readme = "README.md"
requires-python = ">=3.14.6,<3.15"
authors = [{ name = "esemsc-htn223", email = "htn223@ic.ac.uk" }]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/eddy"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = ">=3.14.6,<3.15"
marimo = ">=0.24.0,<0.25"
numpy = ">=2.5.2,<3"
matplotlib = ">=3.11.1,<4"
altair = ">=6.2.2,<7"
geopandas = ">=1.1.4,<2"
requests = ">=2.34.2,<3"
openpyxl = ">=3.1.5,<4"
pandas = ">=3.0.5,<4"
matplotlib-scalebar = ">=0.9.0,<0.10"
folium = ">=0.20.0,<0.21"
ipywidgets = ">=8.1.9,<9"
duckdb = ">=1.5.5,<2"
sqlglot = ">=30.17.0,<31"

[tool.pixi.pypi-dependencies]
eddy-cov = { path = ".", editable = true }
fluxnet-shuttle = { git = "https://github.com/fluxnet/shuttle.git" }
icoscp = ">=0.2.3, <0.3"
